---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Render zrepl configuration file
  template:
    src: zrepl.yml.j2
    dest: /etc/zrepl/zrepl.yml
    mode: "0644"
  vars:
    __zrepl_config:
      global: "{{ zrepl_config_global|d({}) }}"
      jobs: "{{ zrepl_config_jobs|d([]) }}"
  notify: check and restart zrepl


- name: Ensure zrepl is started and enabled
  service:
    name: zrepl
    enabled: "{{ zrepl_service_enabled }}"
    state: "{{ zrepl_service_state }}"
