---
- name: Converge
  hosts: all
  tasks:
    - name: "Include transitiv.zrepl"
      include_role:
        name: "transitiv.zrepl"
  vars:
    zrepl_config_jobs:
      - type: sink
        name: test_sink
        root_fs: "tank/zrepl/test"
        serve:
          type: local
          listener_name: test
